### ISSUE TITLE
Piper scene eventually segfaults

### ISSUE THREAD

**Issue by guillaumetousignant** [guillaumetousignant/another_path_tracer#20]
Seems to depend on time running, not number of iterations.

**Comment by guillaumetousignant** [comment]
#0  Vec3f::operator* (this=0x18150b0d98, scale=scale@entry=0.14890261533873095) at entities/Vec3f.cpp:17
#1  0x00000000080abe4c in Texture_t::get (this=0x85779a0, xy=...) at entities/Texture_t.cpp:57
#2  0x00000000080ebe3a in DiffuseTex_t::bounce (this=0x20590700, uv=..., hit_obj=<optimized out>, ray=...)
    at materials/DiffuseTex_t.cpp:45
#3  0x00000000080ec889 in FresnelMix_t::bounce (this=0x20590f50, uv=..., hit_obj=0x2d2601c0, ray=...)
    at materials/FresnelMix_t.cpp:44
#4  0x000000000808f1dd in Ray_t::raycast (this=this@entry=0x7ffff6ebfd70, scene=scene@entry=0x20590f10, max_bounces=8,
    skybox=0x20590d70) at entities/Ray_t.cpp:33
#5  0x0000000008025804 in CamAperture_t::raytrace(Scene_t const*) [clone ._omp_fn.0] () at cameras/CamAperture_t.cpp:62
#6  0x00007ffffe29695e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#7  0x00007ffffde476db in start_thread (arg=0x7ffff6ec0700) at pthread_create.c:463
#8  0x00007ffffdb6188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by guillaumetousignant** [comment]
Doesn't seem to be texture containing issues at start of program, as looping from 0.0 to 1.0 with get ans *0.9 doesn't cause issues

**Comment by guillaumetousignant** [comment]
Fixed, there was an int underflow in the texture get function
